CREATE TABLE [dbo].[BackupConfig](
	[BackupID] [int] IDENTITY(1,1) NOT NULL,
	[Path] [nvarchar](max) NULL,
	[Date] [date] NULL,
	[Time] [datetime] NULL,
	[IsAutoBackup] [bit] NULL,
 CONSTRAINT [PK_BackupConfig] PRIMARY KEY CLUSTERED 
(
	[BackupID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]

GO