CREATE TABLE [dbo].[ERROR_Log](
	[ERR_ID] [int] IDENTITY(1,1) NOT NULL,
	[ERR_NUMBER] [int] NOT NULL,
	[ERR_SEVERITY] [int] NOT NULL,
	[ERR_STATE] [int] NOT NULL,
	[ERR_LINE] [int] NOT NULL,
	[ERR_MESSAGE] [varchar](max) NOT NULL,
	[ERR_PROCEDURE] [varchar](max) NOT NULL,
	[PARAMERES] [varchar](max) NOT NULL,
	[CreatedOn] [datetime] NOT NULL DEFAULT getdate(),
 CONSTRAINT [PK_ERROR_Log] PRIMARY KEY CLUSTERED 
(
	[ERR_ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]

GO